CREATE TABLE TB_RPJTE_MSG_M (
  MSG_CTN VARCHAR2(4000) NOT NULL,
  LANG_CD VARCHAR2(3) NOT NULL,
  MSG_TXT_CTN VARCHAR2(4000) NOT NULL,
  RMK VARCHAR2(4000) NULL,
  OPT_VAL_CTN1 VARCHAR2(4000) NULL,
  OPT_VAL_CTN2 VARCHAR2(4000) NULL,
  OPT_VAL_CTN3 VARCHAR2(4000) NULL,
  USE_YN VARCHAR2(1) NULL,
  DATA_INS_USER_ID VARCHAR2(50) NULL,
  DATA_INS_USER_IP VARCHAR2(40) NULL,
  DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
  DATA_UPD_USER_ID VARCHAR2(50) NULL,
  DATA_UPD_USER_IP VARCHAR2(40) NULL,
  DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
  CONSTRAINT SYS_C0011706 CHECK ("MSG_CTN" IS NOT NULL),
  CONSTRAINT SYS_C0011707 CHECK ("LANG_CD" IS NOT NULL),
  CONSTRAINT SYS_C0011708 CHECK ("MSG_TXT_CTN" IS NOT NULL),
  CONSTRAINT TB_RPJTE_MSG_M_PK PRIMARY KEY (MSG_CTN,LANG_CD)
);

COMMENT ON COLUMN TB_RPJTE_MSG_M.MSG_CTN IS '메시지코드';
COMMENT ON COLUMN TB_RPJTE_MSG_M.LANG_CD IS '언어코드';
COMMENT ON COLUMN TB_RPJTE_MSG_M.MSG_TXT_CTN IS '메시지명';
COMMENT ON COLUMN TB_RPJTE_MSG_M.RMK IS '비고';
COMMENT ON COLUMN TB_RPJTE_MSG_M.OPT_VAL_CTN1 IS '옵션값내용1';
COMMENT ON COLUMN TB_RPJTE_MSG_M.OPT_VAL_CTN2 IS '옵션값내용2';
COMMENT ON COLUMN TB_RPJTE_MSG_M.OPT_VAL_CTN3 IS '옵션값내용3';
COMMENT ON COLUMN TB_RPJTE_MSG_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MSG_M.DATA_UPD_DTM IS '데이터수정일시';



CREATE TABLE TB_RPJTE_MENU_M (
MNU_ID VARCHAR2(50) NOT NULL,
MNU_NM VARCHAR2(1000) NOT NULL,
MSG_CTN  VARCHAR2(4000) NULL,
MNU_URL VARCHAR2(500) NULL,
MNU_LV_NO NUMBER(10,0) NULL,
UPPR_MNU_ID VARCHAR2(50) NULL,
SORT_ORD NUMBER(10,0) NULL,
MNU_EPS_YN VARCHAR2(1) NULL,
USE_YN VARCHAR2(1) NULL,
MNU_DESC VARCHAR2(200) NULL,
MNU_OPT_VAL_CTN1 VARCHAR2(500),
MNU_OPT_VAL_CTN2 VARCHAR2(500),
MNU_OPT_VAL_CTN3 VARCHAR2(500),
MNU_OPT_VAL_CTN4 VARCHAR2(500),
MNU_OPT_VAL_CTN5 VARCHAR2(500),
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011696 CHECK ("MNU_ID" IS NOT NULL),
CONSTRAINT SYS_C0011697 CHECK ("MNU_NM" IS NOT NULL),
CONSTRAINT TB_RPJTE_MENU_M_PK PRIMARY KEY (MNU_ID)
);

COMMENT ON COLUMN TB_RPJTE_MENU_M.MNU_ID IS '메뉴아이디';
COMMENT ON COLUMN TB_RPJTE_MENU_M.MNU_NM IS '메뉴메시지코드';
comment on column TB_RPJTE_MENU_M.mnu_eps_yn  is '메뉴노출여부';
COMMENT ON COLUMN TB_RPJTE_MENU_M.MNU_URL IS '메뉴경로';
COMMENT ON COLUMN TB_RPJTE_MENU_M.MNU_LV_NO IS '메뉴레벨';
COMMENT ON COLUMN TB_RPJTE_MENU_M.UPPR_MNU_ID IS '상위메뉴아이디';
COMMENT ON COLUMN TB_RPJTE_MENU_M.SORT_ORD IS '메뉴정렬순서번호';
COMMENT ON COLUMN TB_RPJTE_MENU_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_MENU_M.MNU_DESC IS '메뉴설명';
comment on column TB_RPJTE_MENU_M.mnu_opt_val_ctn1 is '메뉴옵션값내용1';
comment on column TB_RPJTE_MENU_M.mnu_opt_val_ctn2 is '메뉴옵션값내용2';
comment on column TB_RPJTE_MENU_M.mnu_opt_val_ctn3 is '메뉴옵션값내용3';
comment on column TB_RPJTE_MENU_M.mnu_opt_val_ctn4 is '메뉴옵션값내용4';
comment on column TB_RPJTE_MENU_M.mnu_opt_val_ctn5 is '메뉴옵션값내용5';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MENU_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_CMN_GR_C (
CMN_GR_CD VARCHAR2(50) NOT NULL,
CMN_GR_CD_NM VARCHAR2(50) NOT NULL,
CMN_GR_CD_DESC VARCHAR2(1000) NULL,
WKT_AREA_DIVS_CD VARCHAR2(50) NULL,
MSG_CTN VARCHAR2(4000),
SORT_ORD NUMBER(10,0) NULL,
OPT_VAL_NM1 VARCHAR2(100) NULL,
OPT_VAL_NM2 VARCHAR2(100) NULL,
OPT_VAL_NM3 VARCHAR2(100) NULL,
OPT_VAL_NM4 VARCHAR2(100) NULL,
OPT_VAL_NM5 VARCHAR2(100) NULL,
OPT_VAL_NM6 VARCHAR2(100) NULL,
OPT_VAL_NM7 VARCHAR2(100) NULL,
OPT_VAL_NM8 VARCHAR2(100) NULL,
OPT_VAL_NM9 VARCHAR2(100) NULL,
OPT_VAL_NM10 VARCHAR2(100) NULL,
OPT_VAL_NM11 VARCHAR2(100) NULL,
OPT_VAL_NM12 VARCHAR2(100) NULL,
OPT_VAL_NM13 VARCHAR2(100) NULL,
OPT_VAL_NM14 VARCHAR2(100) NULL,
OPT_VAL_NM15 VARCHAR2(100) NULL,
RMK VARCHAR2(4000) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011698 CHECK ("CMN_GR_CD" IS NOT NULL),
CONSTRAINT SYS_C0011699 CHECK ("CMN_GR_CD_NM" IS NOT NULL),
CONSTRAINT TB_RPJTE_CMN_GR_C_PK PRIMARY KEY (CMN_GR_CD)
);

COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.CMN_GR_CD IS '공통그룹코드';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.CMN_GR_CD_NM IS '공통그룹코드명';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.CMN_GR_CD_DESC IS '공통그룹코드설명';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.WKT_AREA_DIVS_CD IS '업무영역구분코드';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.MSG_CTN IS '메세지내용';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM1 IS '옵션값명1';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM2 IS '옵션값명2';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM3 IS '옵션값명3';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM4 IS '옵션값명4';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM5 IS '옵션값명5';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM6 IS '옵션값명6';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM7 IS '옵션값명7';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM8 IS '옵션값명8';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM9 IS '옵션값명9';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM10 IS '옵션값명10';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM11 IS '옵션값명11';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM12 IS '옵션값명12';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM13 IS '옵션값명13';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM14 IS '옵션값명14';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.OPT_VAL_NM15 IS '옵션값명15';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.RMK IS '비고';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_CMN_GR_C.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_CMN_C (
CMN_GR_CD VARCHAR2(50) NOT NULL,
CMN_CD VARCHAR2(150) NOT NULL,
CMN_CD_NM VARCHAR2(200) NOT NULL,
CMN_CD_DESC VARCHAR2(400) NULL,
UPPR_CMN_CD VARCHAR2(150) NULL,
MSG_CTN VARCHAR2(4000),
SORT_ORD NUMBER(10,0) NULL,
USE_YN VARCHAR2(1) NULL,
OPT_VAL_CTN1 VARCHAR2(4000) NULL,
OPT_VAL_CTN2 VARCHAR2(4000) NULL,
OPT_VAL_CTN3 VARCHAR2(4000) NULL,
OPT_VAL_CTN4 VARCHAR2(4000) NULL,
OPT_VAL_CTN5 VARCHAR2(4000) NULL,
OPT_VAL_CTN6 VARCHAR2(4000) NULL,
OPT_VAL_CTN7 VARCHAR2(4000) NULL,
OPT_VAL_CTN8 VARCHAR2(4000) NULL,
OPT_VAL_CTN9 VARCHAR2(4000) NULL,
OPT_VAL_CTN10 VARCHAR2(4000) NULL,
OPT_VAL_CTN11 VARCHAR2(4000) NULL,
OPT_VAL_CTN12 VARCHAR2(4000) NULL,
OPT_VAL_CTN13 VARCHAR2(4000) NULL,
OPT_VAL_CTN14 VARCHAR2(4000) NULL,
OPT_VAL_CTN15 VARCHAR2(4000) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011701 CHECK ("CMN_GR_CD" IS NOT NULL),
CONSTRAINT SYS_C0011702 CHECK ("CMN_CD" IS NOT NULL),
CONSTRAINT SYS_C0011779 CHECK ("CMN_CD_NM" IS NOT NULL),
CONSTRAINT TB_RPJTE_CMN_C_PK PRIMARY KEY (CMN_GR_CD,CMN_CD)
);

COMMENT ON COLUMN TB_RPJTE_CMN_C.CMN_GR_CD IS '공통그룹코드';
COMMENT ON COLUMN TB_RPJTE_CMN_C.CMN_CD IS '공통코드';
COMMENT ON COLUMN TB_RPJTE_CMN_C.CMN_CD_NM IS '공통코드명';
COMMENT ON COLUMN TB_RPJTE_CMN_C.CMN_CD_DESC IS '공통코드설명';
COMMENT ON COLUMN TB_RPJTE_CMN_C.UPPR_CMN_CD IS '상위공통코드';
COMMENT ON COLUMN TB_RPJTE_CMN_C.MSG_CTN IS '메세지내용';
COMMENT ON COLUMN TB_RPJTE_CMN_C.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_RPJTE_CMN_C.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN1 IS '옵션값내용1';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN2 IS '옵션값내용2';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN3 IS '옵션값내용3';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN4 IS '옵션값내용4';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN5 IS '옵션값내용5';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN6 IS '옵션값내용6';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN7 IS '옵션값내용7';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN8 IS '옵션값내용8';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN9 IS '옵션값내용9';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN10 IS '옵션값내용10';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN11 IS '옵션값내용11';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN12 IS '옵션값내용12';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN13 IS '옵션값내용13';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN14 IS '옵션값내용14';
COMMENT ON COLUMN TB_RPJTE_CMN_C.OPT_VAL_CTN15 IS '옵션값내용15';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_CMN_C.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_DEPT_M (
DEPT_CD VARCHAR2(20) NOT NULL,
COP_CD VARCHAR2(10) NOT NULL,
DEPT_NM VARCHAR2(300) NULL,
DEPT_ENG_NM VARCHAR2(300) NULL,
DEPT_CNG_NM VARCHAR2(300) NULL,
TEM_LDR_USER_ID VARCHAR2(50) NULL,
UPPR_DEPT_CD VARCHAR2(20) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011713 CHECK ("DEPT_CD" IS NOT NULL),
CONSTRAINT SYS_C0011714 CHECK ("COP_CD" IS NOT NULL),
CONSTRAINT TB_RPJTE_DEPT_M_PK PRIMARY KEY (DEPT_CD)
);

COMMENT ON COLUMN TB_RPJTE_DEPT_M.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.COP_CD IS '사업부코드';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DEPT_NM IS '부서명';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DEPT_ENG_NM IS '부서영문명';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DEPT_CNG_NM IS '부서중문명';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.TEM_LDR_USER_ID IS '팀리더사용자ID';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.UPPR_DEPT_CD IS '상위부서코드';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.USE_YN IS '유효여부';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_DEPT_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_EMP_M (
USER_ID VARCHAR2(50) NOT NULL,
EMP_NO VARCHAR2(20) NULL,
EMP_NM VARCHAR2(50) NULL,
EMP_ENG_NM VARCHAR2(100) NULL,
EMP_CNG_NM VARCHAR2(100) NULL,
DEPT_CD VARCHAR2(20) NULL,
DEPT_NM VARCHAR2(300) NULL,
DEPT_ENG_NM VARCHAR2(300) NULL,
DEPT_CNG_NM VARCHAR2(300) NULL,
COP_CD VARCHAR2(10) NULL,
JTI_CD VARCHAR2(10) NULL,
JTI_NM VARCHAR2(200) NULL,
JTI_ENG_NM VARCHAR2(50) NULL,
JTI_CNG_NM VARCHAR2(50) NULL,
JPS_CD VARCHAR2(10) NULL,
JPS_NM VARCHAR2(200) NULL,
JPS_ENG_NM VARCHAR2(50) NULL,
JPS_CNG_NM VARCHAR2(50) NULL,
INO_STAT_CD VARCHAR2(20) NULL,
JCOM_DT VARCHAR2(8) NULL,
RSGN_DT VARCHAR2(8) NULL,
UPPR_EMP_NO VARCHAR2(20) NULL,
ONDU_REGN_CD VARCHAR2(50) NULL,
ONDU_REGN_NM VARCHAR2(50) NULL,
SSO_DTPL_NM VARCHAR2(100) NULL,
HME_TANO VARCHAR2(10) NULL,
HME_PHN VARCHAR2(50) NULL,
OFC_TANO VARCHAR2(10) NULL,
OFC_PHN VARCHAR2(50) NULL,
OFC_ETN_PHN VARCHAR2(50) NULL,
DOC_AUTH_CD VARCHAR2(20) NULL,
EML_SVR_DMN_IFO_NM VARCHAR2(200) NULL,
INO_DIVS_CD VARCHAR2(20) NULL,
EMP_HPHN VARCHAR2(50) NULL,
OLD_DEPT_CD VARCHAR2(20) NULL,
OLD_EMP_NO VARCHAR2(20) NULL,
DEPT_ENG_DESC VARCHAR2(100) NULL,
EMP_LOWR_GR_CD VARCHAR2(50) NULL,
EMP_UPPR_GR_CD VARCHAR2(50) NULL,
EML_DMN_IFO_NM VARCHAR2(200) NULL,
SSO_DTPL_CD VARCHAR2(50) NULL,
SSO_EMP_CNG_NM VARCHAR2(100) NULL,
CTRY_CD VARCHAR2(10) NULL,
SSO_CHG_TP_CD VARCHAR2(50) NULL,
SSO_CHG_DT VARCHAR2(8) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011715 CHECK ("USER_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_EMP_M_PK PRIMARY KEY (USER_ID)
);

COMMENT ON COLUMN TB_RPJTE_EMP_M.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_NO IS '사원번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_NM IS '사원명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_ENG_NM IS '사원영문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_CNG_NM IS '사원중문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DEPT_NM IS '부서명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DEPT_ENG_NM IS '부서영문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DEPT_CNG_NM IS '부서중문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.COP_CD IS '법인코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JTI_CD IS '직위코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JTI_NM IS '직위명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JTI_ENG_NM IS '직위영문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JTI_CNG_NM IS '직위중문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JPS_CD IS '직책코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JPS_NM IS '직책명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JPS_ENG_NM IS '직책영문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JPS_CNG_NM IS '직책중문명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.INO_STAT_CD IS '재직상태코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.JCOM_DT IS '입사일자';
COMMENT ON COLUMN TB_RPJTE_EMP_M.RSGN_DT IS '퇴사일자';
COMMENT ON COLUMN TB_RPJTE_EMP_M.UPPR_EMP_NO IS '상위자사번';
COMMENT ON COLUMN TB_RPJTE_EMP_M.ONDU_REGN_CD IS '근무지역코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.ONDU_REGN_NM IS '근무지역명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.SSO_DTPL_NM IS 'MYINFO위치';
COMMENT ON COLUMN TB_RPJTE_EMP_M.HME_TANO IS '자택전화지역번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.HME_PHN IS '자택전화번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.OFC_TANO IS '사무실전화지역번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.OFC_PHN IS '사무실전화번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.OFC_ETN_PHN IS '내선번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DOC_AUTH_CD IS '문서권한코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EML_SVR_DMN_IFO_NM IS '메일서버정보';
COMMENT ON COLUMN TB_RPJTE_EMP_M.INO_DIVS_CD IS '재직구분코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_HPHN IS '사원휴대전화번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.OLD_DEPT_CD IS '변경전부서코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.OLD_EMP_NO IS '변경전사원번호';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DEPT_ENG_DESC IS '부서영어설명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_LOWR_GR_CD IS '사원하위그룹코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EMP_UPPR_GR_CD IS '사원상위그룹코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.EML_DMN_IFO_NM IS '이메일도메인정보명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.SSO_DTPL_CD IS 'SSO근무지코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.SSO_EMP_CNG_NM IS 'SSO사원중국어명';
COMMENT ON COLUMN TB_RPJTE_EMP_M.CTRY_CD IS '국가코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.SSO_CHG_TP_CD IS 'SSO변경유형코드';
COMMENT ON COLUMN TB_RPJTE_EMP_M.SSO_CHG_DT IS 'SSO변경일자';
COMMENT ON COLUMN TB_RPJTE_EMP_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EMP_M.DATA_UPD_DTM IS '데이터수정일시';

create table TB_RPJTE_APR_TPL_M
(
APR_TPL_ID VARCHAR2(50) NOT NULL,
INTG_APR_TP_CD VARCHAR2(50) NULL,
EAPR_TPL_ID  VARCHAR2(50) NULL,
APR_TPL_NM VARCHAR2(200) NULL,
SORT_ORD NUMBER(10,0) NULL,
APR_TPL_DESC VARCHAR2(200) NULL,
USE_YN VARCHAR2(1) NULL,
PRS_DESC VARCHAR2(4000) NULL,
WCST_USE_YN VARCHAR2(1) NULL,
WCST_DESC CLOB NULL,
NOTF_USE_YN VARCHAR2(1) NULL,
NTDK_ID NUMBER(10,0) NULL,
MGR_USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011726 CHECK ("APR_TPL_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_TPL_M_PK PRIMARY KEY (APR_TPL_ID)
);

COMMENT ON TABLE TB_RPJTE_APR_TPL_M
IS '결재양식기본';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.APR_TPL_ID
IS '결재양식ID';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.INTG_APR_TP_CD
IS '통합결재유형코드';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.EAPR_TPL_ID
IS '전자결재양식ID';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.APR_TPL_NM
IS '결재양식명';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.SORT_ORD
IS '정렬순서';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.APR_TPL_DESC
IS '결재양식설명';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.USE_YN
IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.PRS_DESC
IS '프로세스설명';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.WCST_USE_YN
IS '동의서사용여부';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.WCST_DESC
IS '동의서설명';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.NOTF_USE_YN
IS '통보사용여부';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.NTDK_ID
IS '통보처ID';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.MGR_USE_YN
IS '담당자사용여부';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_TPL_M.DATA_UPD_DTM
IS '데이터수정일시';


CREATE TABLE TB_RPJTE_NTDK_M (
NTDK_ID NUMBER(10,0) NOT NULL,
NTDK_NM VARCHAR2(200) NULL,
NTDK_DESC VARCHAR2(200) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011728 CHECK ("NTDK_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_NTDK_M_PK PRIMARY KEY (NTDK_ID)
);

COMMENT ON COLUMN TB_RPJTE_NTDK_M.NTDK_ID IS '통보처아이디';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.NTDK_NM IS '통보처제목';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.NTDK_DESC IS '통보처설명';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_NTDK_M.DATA_UPD_DTM IS '데이터수정일시';

create table TB_RPJTE_NTDK_D
(
NTDK_ID          NUMBER(10,0) NOT NULL,
NTDK_SEQ         NUMBER(18,0) NOT NULL,
NTDK_DIVS_CD     VARCHAR2(50) NULL,
APR_NOTF_USER_ID VARCHAR2(50) NOT NULL,
SORT_ORD         NUMBER(10) NULL,
USE_YN           VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011730 CHECK ("NTDK_ID" IS NOT NULL),
CONSTRAINT SYS_C0011731 CHECK ("NTDK_SEQ" IS NOT NULL),
CONSTRAINT SYS_C0011732 CHECK ("APR_NOTF_USER_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_NTDK_D_PK PRIMARY KEY (NTDK_ID,NTDK_SEQ)

);
COMMENT ON TABLE TB_RPJTE_NTDK_D
IS '통보처상세';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.NTDK_ID
IS '통보처ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.NTDK_SEQ
IS '통보처순번';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.NTDK_DIVS_CD
IS '통보처구분코드';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.APR_NOTF_USER_ID
IS '결재통보사용자ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.SORT_ORD
IS '정렬순서';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.USE_YN
IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_NTDK_D.DATA_UPD_DTM
IS '데이터수정일시';


create table TB_RPJTE_APR_RULE_M
(
APR_RULE_ID          VARCHAR2(50) NOT NULL,
APR_RULE_NM          VARCHAR2(200) NOT NULL,
APR_LN_ADD_PMIT_YN   VARCHAR2(1) NOT NULL,
APR_RFER_ADD_PSBL_YN VARCHAR2(1) NOT NULL,
APR_LN_RSTB_PMIT_YN  VARCHAR2(1) NOT NULL,
APR_LN_DUPL_PMIT_YN  VARCHAR2(1) NOT NULL,
APR_EXC_TGT_ID       VARCHAR2(50) NULL,
MST_NTDK_ID          NUMBER(10,0) NULL,
DATA_INS_USER_ID     VARCHAR2(50) NULL,
DATA_INS_USER_IP     VARCHAR2(40) NULL,
DATA_INS_DTM         DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID     VARCHAR2(50),
DATA_UPD_USER_IP     VARCHAR2(40),
DATA_UPD_DTM         DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011734 CHECK ("APR_RULE_ID" IS NOT NULL),
CONSTRAINT SYS_C0011735 CHECK ("APR_RULE_NM" IS NOT NULL),
CONSTRAINT SYS_C0011736 CHECK ("APR_LN_ADD_PMIT_YN" IS NOT NULL),
CONSTRAINT SYS_C0011737 CHECK ("APR_RFER_ADD_PSBL_YN" IS NOT NULL),
CONSTRAINT SYS_C0011738 CHECK ("APR_LN_RSTB_PMIT_YN" IS NOT NULL),
CONSTRAINT SYS_C0011739 CHECK ("APR_LN_DUPL_PMIT_YN" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_RULE_M_PK PRIMARY KEY (APR_RULE_ID)
);
COMMENT ON TABLE TB_RPJTE_APR_RULE_M
IS '결재규칙기본';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_RULE_ID
IS '결재규칙ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_RULE_NM
IS '결재규칙명';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_LN_ADD_PMIT_YN
IS '결재라인추가허용여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_RFER_ADD_PSBL_YN
IS '결재참조자추가가능여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_LN_RSTB_PMIT_YN
IS '결재라인재설정허용여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_LN_DUPL_PMIT_YN
IS '결재라인중복허용여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.APR_EXC_TGT_ID
IS '결재제외ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.MST_NTDK_ID
IS '기본통보처ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_M.DATA_UPD_DTM
IS '데이터수정일시';


create table TB_RPJTE_APR_RULE_D
(
APR_RULE_ID        VARCHAR2(50) NOT NULL,
APR_LN_ID          VARCHAR2(30) NOT NULL,
APR_TP_DIVS_CD     VARCHAR2(20) NULL,
PRL_YN             VARCHAR2(1) NULL,
APR_LN_SNB         NUMBER(18,5) NULL,
APR_LN_SEQ         NUMBER(18,0) NULL,
APR_LN_ROLE_CD     VARCHAR2(10) NULL,
DEPT_CD            VARCHAR2(20) NULL,
USER_ID            VARCHAR2(50) NULL,
APR_LN_CHG_PSBL_YN VARCHAR2(1) NULL,
APR_LN_DEL_PSBL_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID   VARCHAR2(50) NULL,
DATA_INS_USER_IP   VARCHAR2(40) NULL,
DATA_INS_DTM       DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID   VARCHAR2(50) NULL,
DATA_UPD_USER_IP   VARCHAR2(40) NULL,
DATA_UPD_DTM       DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011742 CHECK ("APR_RULE_ID" IS NOT NULL),
CONSTRAINT SYS_C0011743 CHECK ("APR_LN_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_RULE_D_PK PRIMARY KEY (APR_RULE_ID,APR_LN_ID)
);

COMMENT ON TABLE TB_RPJTE_APR_RULE_D
IS '결재규칙상세';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_RULE_ID
IS '결재규칙ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_ID
IS '결재라인ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_TP_DIVS_CD
IS '결재유형구분코드';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.PRL_YN
IS '병렬여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_SNB
IS '결재라인차수';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_SEQ
IS '결재라인순번';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_ROLE_CD
IS '결재라인역할코드';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DEPT_CD
IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.USER_ID
IS '사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_CHG_PSBL_YN
IS '결재라인변경가능여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.APR_LN_DEL_PSBL_YN
IS '결재라인삭제가능여부';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_D.DATA_UPD_DTM
IS '데이터수정일시';


CREATE TABLE TB_RPJTE_APR_RULE_EXC_M
(
APR_EXC_TGT_ID   VARCHAR2(50) NOT NULL,
APR_EXC_NM       VARCHAR2(20) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL,
CONSTRAINT TB_RPJTE_APR_RULE_EXC_M_PK PRIMARY KEY (APR_EXC_TGT_ID)
);
COMMENT ON TABLE TB_RPJTE_APR_RULE_EXC_M
IS '결재규칙제외기본';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.APR_EXC_TGT_ID
IS '결재제외대상ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.APR_EXC_NM
IS '결재제외명';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE TABLE TB_RPJTE_APR_RULE_EXC_D
(
APR_EXC_TGT_ID   VARCHAR2(50) NOT NULL,
APR_EXC_SEQ      NUMBER(18) NOT NULL,
APR_EXC_DIVS_CD  VARCHAR2(20) NOT NULL,
APR_EXC_USER_ID  VARCHAR2(50) NULL,
APR_EXC_JTI_CD   VARCHAR2(10) NULL,
APR_EXC_JPS_CD   VARCHAR2(10) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011746 CHECK ("APR_EXC_TGT_ID" IS NOT NULL),
CONSTRAINT SYS_C0011747 CHECK ("APR_EXC_SEQ" IS NOT NULL),
CONSTRAINT SYS_C0011748 CHECK ("APR_EXC_DIVS_CD" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_RULE_EXC_D_PK PRIMARY KEY (APR_EXC_TGT_ID, APR_EXC_SEQ)

);
COMMENT ON TABLE TB_RPJTE_APR_RULE_EXC_D
IS '결재규칙제외상세';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_TGT_ID
IS '결재제외대상ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_SEQ
IS '결재제외순번';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_DIVS_CD
IS '결재제외구분코드(직급, 직책, 사용자)';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_USER_ID
IS '결재제외사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_JTI_CD
IS '결재제외직위코드';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.APR_EXC_JPS_CD
IS '결재제외직책코드';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_RULE_EXC_D.DATA_UPD_DTM
IS '데이터수정일시';

CREATE TABLE TB_RPJTE_APR_REQ_M
(
APR_REQ_ID           VARCHAR2(50) NOT NULL,
APR_TPL_ID           VARCHAR2(50) NULL,
EAPR_DOC_NO          VARCHAR2(50) NULL,
APR_REQ_USER_ID      VARCHAR2(50) NULL,
APR_PVN_DDLN_CD      VARCHAR2(50) NULL,
DEPT_CD              VARCHAR2(20) NULL,
DEPT_NM              VARCHAR2(300) NULL,
ONDU_REGN_CD         VARCHAR2(50) NULL,
ONDU_REGN_NM         VARCHAR2(50) NULL,
APR_REQ_TIT_NM       VARCHAR2(200) NULL,
TRNM_BDY_CTN         CLOB NULL,
APR_REQ_DESC         VARCHAR2(4000) NULL,
APR_REQ_DTM          DATE NULL,
WCST_CNC_YN          VARCHAR2(1) NULL,
APR_REQ_PROG_STAT_CD VARCHAR2(50) NULL,
WKT_SCRN_URL         VARCHAR2(500) NULL,
APR_WAIT_SCRN_URL    VARCHAR2(500) NULL,
MBIL_WKT_SCRN_URL    VARCHAR2(500) NULL,
APR_FILE_GR_ID       VARCHAR2(50) NULL,
REF_APR_REQ_ID       VARCHAR2(50) NULL,
OPT_VAL_CTN1         VARCHAR2(4000) NULL,
OPT_VAL_CTN2         VARCHAR2(4000) NULL,
OPT_VAL_CTN3         VARCHAR2(4000) NULL,
OPT_VAL_CTN4         VARCHAR2(4000) NULL,
OPT_VAL_CTN5         VARCHAR2(4000) NULL,
DATA_INS_USER_ID     VARCHAR2(50) NULL,
DATA_INS_USER_IP     VARCHAR2(40) NULL,
DATA_INS_DTM         DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID     VARCHAR2(50) NULL,
DATA_UPD_USER_IP     VARCHAR2(40) NULL,
DATA_UPD_DTM         DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011756 CHECK ("APR_REQ_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_REQ_M_PK PRIMARY KEY (APR_REQ_ID)

);

COMMENT ON TABLE TB_RPJTE_APR_REQ_M
IS '결재 요청 기본';

COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_ID
IS '결재요청ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_TPL_ID
IS '결재양식ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.EAPR_DOC_NO
IS '전자결재문서번호';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_USER_ID
IS '결재요청사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_PVN_DDLN_CD
IS '결재보존기한코드';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DEPT_CD
IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DEPT_NM
IS '부서명';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.ONDU_REGN_CD
IS '근무지역코드';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.ONDU_REGN_NM
IS '근무지역명';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_TIT_NM
IS '결재요청제목명';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.TRNM_BDY_CTN
IS '전송본문내용';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_DESC
IS '결재요청설명';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_DTM
IS '결재요청일시';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.WCST_CNC_YN
IS '동의서동의여부';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_REQ_PROG_STAT_CD
IS '결재요청진행상태코드';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.WKT_SCRN_URL
IS '업무화면URL주소';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_WAIT_SCRN_URL
IS '결재대기화면URL주소';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.MBIL_WKT_SCRN_URL
IS '모바일업무화면URL주소';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.APR_FILE_GR_ID
IS '결재파일그룹ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.REF_APR_REQ_ID
IS '참조결재요청ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.OPT_VAL_CTN1
IS '옵션값내용1(사용:추가결재파일그룹ID)';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.OPT_VAL_CTN2
IS '옵션값내용2';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.OPT_VAL_CTN3
IS '옵션값내용3';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.OPT_VAL_CTN4
IS '옵션값내용4';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.OPT_VAL_CTN5
IS '옵션값내용5';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_REQ_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE TABLE TB_RPJTE_APR_LN_M
(
APR_REQ_ID             VARCHAR2(50) NOT NULL,
APR_LN_SEQ             NUMBER(18,0) NOT NULL,
APR_LN_SNB             NUMBER(18,5) NULL,
GRNR_APR_TP_DIVS_CD    VARCHAR2(1) NULL,
APR_FFIL_TP_CD         VARCHAR2(50) NULL,
PRL_YN                 VARCHAR2(1) NULL,
APR_APRV_USER_ID       VARCHAR2(50) NULL,
APR_PSG_STAT_CD        VARCHAR2(30) NULL,
APR_APRV_DTM           DATE NULL,
APR_APRV_OPIN_UTF8_CTN VARCHAR2(1000) NULL,
APR_DLGT_USER_ID       VARCHAR2(50) NULL,
APR_DLGT_NO            NUMBER(20) NULL,
APR_LN_DIVS_CD         VARCHAR2(20) NULL,
EML_SNDO_SEQ           NUMBER(18) NULL,
DATA_INS_USER_ID       VARCHAR2(50) NULL,
DATA_INS_USER_IP       VARCHAR2(40) NULL,
DATA_INS_DTM           DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID       VARCHAR2(50) NULL,
DATA_UPD_USER_IP       VARCHAR2(40) NULL,
DATA_UPD_DTM           DATE DEFAULT SYSDATE NULL,
CONSTRAINT SYS_C0011751 CHECK ("APR_REQ_ID" IS NOT NULL),
CONSTRAINT SYS_C0011752 CHECK ("APR_LN_SEQ" IS NOT NULL),
CONSTRAINT TB_RPJTE_APR_LN_M_PK PRIMARY KEY (APR_REQ_ID,APR_LN_SEQ)

);

COMMENT ON TABLE TB_RPJTE_APR_LN_M
IS '결재라인기본';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_REQ_ID
IS '결재요청ID';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_LN_SEQ
IS '결재라인순번';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_LN_SNB
IS '결재라인차수';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.GRNR_APR_TP_DIVS_CD
IS '승인자결재유형구분코드';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_FFIL_TP_CD
IS '결재수행유형코드';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.PRL_YN
IS '병렬여부';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_APRV_USER_ID
IS '결재승인사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_PSG_STAT_CD
IS '결재처리상태코드';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_APRV_DTM
IS '결재승인일시';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_APRV_OPIN_UTF8_CTN
IS '결재승인의견UTF8내용';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_DLGT_USER_ID
IS '결재위임사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_DLGT_NO
IS '결재위임번호';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.APR_LN_DIVS_CD
IS '결재라인구분코드';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.EML_SNDO_SEQ
IS '이메일발송순번';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_LN_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE TABLE TB_RPJTE_ATCH_FILE_M (
ATCH_FILE_GR_ID VARCHAR2(50) NOT NULL,
ATCH_FILE_ID VARCHAR2(50) NOT NULL,
ATCH_FILE_NM VARCHAR2(500) NULL,
SORT_ORD NUMBER(10,0) NULL,
ATCH_FILE_SAVE_LOC_DIVS_CD VARCHAR2(20) NULL,
ATCH_FILE_SAVE_NM VARCHAR2(500) NULL,
ATCH_FILE_SIZE NUMBER NULL,
ATCH_FILE_EFNM_NM VARCHAR2(100) NULL,
ATCH_FILE_SAVE_PATH_CTN VARCHAR2(4000) NULL,
ATCH_FILE_TP_CD VARCHAR2(20) NULL,
OPT_VAL_CTN1 VARCHAR2(4000) NULL,
OPT_VAL_CTN2 VARCHAR2(4000) NULL,
OPT_VAL_CTN3 VARCHAR2(4000) NULL,
OPT_VAL_CTN4 VARCHAR2(4000) NULL,
OPT_VAL_CTN5 VARCHAR2(4000) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011758 CHECK ("ATCH_FILE_GR_ID" IS NOT NULL),
CONSTRAINT SYS_C0011759 CHECK ("ATCH_FILE_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_ATCH_FILE_M_PK PRIMARY KEY (ATCH_FILE_GR_ID,ATCH_FILE_ID)

);


COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_GR_ID IS '첨부파일그룹ID';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_ID IS '첨부파일ID';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_NM IS '첨부파일명';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_SAVE_LOC_DIVS_CD IS '첨부파일저장위치구분코드';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_SAVE_NM IS '첨부파일저장명';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_SIZE IS '첨부파일크기';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_EFNM_NM IS '첨부파일확장자명';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_SAVE_PATH_CTN IS '첨부파일저장경로내용';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.ATCH_FILE_TP_CD IS '첨부파일유형코드';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.OPT_VAL_CTN1 IS '옵션값내용1';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.OPT_VAL_CTN2 IS '옵션값내용2';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.OPT_VAL_CTN3 IS '옵션값내용3';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.OPT_VAL_CTN4 IS '옵션값내용4';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.OPT_VAL_CTN5 IS '옵션값내용5';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ATCH_FILE_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_HR_DEPT_I (
CODE_NAME_CN VARCHAR2(200) NULL,
CODE_NAME_EN VARCHAR2(200) NULL,
CODE_NAME_KO VARCHAR2(200) NULL,
CODE_NUMB VARCHAR2(10) NULL,
CODE_UPER VARCHAR2(10) NULL,
CREATEDATE VARCHAR2(10) NULL,
DIVISION VARCHAR2(8) NULL,
UPDATEDATE VARCHAR2(10) NULL,
VALID_FLAG VARCHAR2(5) NULL,
CHIEF_NUMB VARCHAR2(16) NULL,
IF_CREATION_DATE DATE NULL,
TRANSFER_FLAG VARCHAR2(1) NULL,
TRANSFER_DATE DATE NULL,
IF_ID NUMBER NULL
);


COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CODE_NAME_CN IS '부서명_중국어';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CODE_NAME_EN IS '부서명_영어';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CODE_NAME_KO IS '부서명_한글';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CODE_NUMB IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CODE_UPER IS '상위부서코드';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CREATEDATE IS '생성일';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.DIVISION IS '구분(C100외는 중국)';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.UPDATEDATE IS '수정일';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.VALID_FLAG IS '사용유무';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.CHIEF_NUMB IS '팀 리더사번';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.IF_CREATION_DATE IS '인터페이스 수신일시';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.TRANSFER_FLAG IS '마스터 반영 여부';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.TRANSFER_DATE IS '마스터 반영 일시';
COMMENT ON COLUMN TB_RPJTE_HR_DEPT_I.IF_ID IS '인터페이스 순번';


CREATE TABLE TB_RPJTE_HR_EMP_I (
SA_COMP VARCHAR2(8) NULL,
SA_DEPT VARCHAR2(8) NULL,
SA_DEPT_NAME VARCHAR2(100) NULL,
SA_DEPT_NAME_C VARCHAR2(200) NULL,
SA_DEPT_NAME_E VARCHAR2(200) NULL,
SA_DEPT_NEW VARCHAR2(8) NULL,
SA_EDEPT_NAME VARCHAR2(150) NULL,
SA_FUNC VARCHAR2(4) NULL,
SA_FUNC_NAME VARCHAR2(80) NULL,
SA_FUNC_NAME_C VARCHAR2(80) NULL,
SA_FUNC_NAME_E VARCHAR2(80) NULL,
SA_HAND VARCHAR2(30) NULL,
SA_HNAME VARCHAR2(30) NULL,
SA_JOBX VARCHAR2(5) NULL,
SA_JOBX_NAME VARCHAR2(80) NULL,
SA_JOBX_NAME_C VARCHAR2(80) NULL,
SA_JOBX_NAME_E VARCHAR2(80) NULL,
SA_NAME VARCHAR2(30) NULL,
SA_NAME_E VARCHAR2(30) NULL,
SA_PHON_AREA VARCHAR2(20) NULL,
SA_PHON_D VARCHAR2(50) NULL,
SA_PHON_H VARCHAR2(50) NULL,
SA_PHON_HAREA VARCHAR2(20) NULL,
SA_PHON_O VARCHAR2(50) NULL,
SA_RECT VARCHAR2(8) NULL,
SA_SABUN VARCHAR2(16) NULL,
SA_SABUN_LEADER VARCHAR2(16) NULL,
SA_SABUN_NEW VARCHAR2(16) NULL,
SA_SYSTEM VARCHAR2(4) NULL,
SA_TEMP VARCHAR2(2) NULL,
SA_TEMP_DATE VARCHAR2(8) NULL,
SA_USER VARCHAR2(20) NULL,
SSO_EX_FLAG VARCHAR2(2) NULL,
SSO_MAILSERVER VARCHAR2(50) NULL,
SSO_PS_DATE VARCHAR2(8) NULL,
SA_GNMU VARCHAR2(8) NULL,
SA_GNMU_NAME VARCHAR2(80) NULL,
SSO_LOCATE VARCHAR2(75) NULL,
SA_PAYXGB CHAR(1) NULL,
SA_SNBNGB CHAR(2) NULL,
SA_SNBNGR CHAR(1) NULL,
SA_MAIL VARCHAR2(100) NULL,
SSO_SU_GNMU VARCHAR2(4) NULL,
SSO_CNAME VARCHAR2(50) NULL,
SA_NATIONALITY VARCHAR2(10) NULL,
IF_CREATION_DATE DATE NULL,
TRANSFER_FLAG VARCHAR2(1) NULL,
TRANSFER_DATE DATE NULL,
IF_ID NUMBER(22,0) NULL
);

COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_COMP IS '법인 코드';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_DEPT IS '부서코드(옛날부서)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_DEPT_NAME IS '부서명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_DEPT_NAME_C IS '부서 중문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_DEPT_NAME_E IS '부서 영문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_DEPT_NEW IS '부서코드(현재부서코드)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_EDEPT_NAME IS '영문 부서명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_FUNC IS '직책';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_FUNC_NAME IS '직책명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_FUNC_NAME_C IS '직책 중문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_FUNC_NAME_E IS '직책영문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_HAND IS '핸드폰 번호(보안으로 데이터값 없음)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_HNAME IS '이름 중문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_JOBX IS '직위코드';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_JOBX_NAME IS '직위명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_JOBX_NAME_C IS '직위중문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_JOBX_NAME_E IS '직위영문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_NAME IS '이름';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_NAME_E IS '영문이름';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PHON_AREA IS '지역 번호(집 전화)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PHON_D IS '전화번호2(내선번호)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PHON_H IS '전화번호3(집전화번호)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PHON_HAREA IS '지역 번호(사무실 전화)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PHON_O IS '전화번호1(사무실전화번호)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_RECT IS '입사날자';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SABUN IS '사번(옛날 사번)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SABUN_LEADER IS '상급자 사번';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SABUN_NEW IS '사번(현재 사번)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SYSTEM IS '문서중앙화 권한';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_TEMP IS '입사현황';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_TEMP_DATE IS '퇴직날자';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_USER IS 'ID';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_EX_FLAG IS '정보 변경 코드(C생성, U:변경, D:삭제)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_MAILSERVER IS '메일 서버';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_PS_DATE IS '변경날짜';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_GNMU IS '인사정보상 근무지코드';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_GNMU_NAME IS '인사정보상 근무지';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_LOCATE IS 'MYINFO상 근무지';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_PAYXGB IS '생산직,사무직구분(사무직:E, 생산/기술직:H)';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SNBNGB IS '사원하위그룹';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_SNBNGR IS '사원상위그룹';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_MAIL IS 'EMAIL 도메인';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_SU_GNMU IS 'SSO 근무지코드';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SSO_CNAME IS 'SSO 이름 중문명';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.SA_NATIONALITY IS '국가구분';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.IF_CREATION_DATE IS '인터페이스 수신일시';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.TRANSFER_FLAG IS '마스터 반영 여부';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.TRANSFER_DATE IS '마스터 반영 일시';
COMMENT ON COLUMN TB_RPJTE_HR_EMP_I.IF_ID IS '인터페이스 순번';


CREATE TABLE TB_RPJTE_ROLE_M (
ROLE_CD VARCHAR2(20) NOT NULL,
ROLE_NM VARCHAR2(400) NULL,
ROLE_DESC VARCHAR2(4000) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011761 CHECK ("ROLE_CD" IS NOT NULL),
CONSTRAINT TB_RPJTE_ROLE_M_PK PRIMARY KEY (ROLE_CD)
);


COMMENT ON COLUMN TB_RPJTE_ROLE_M.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.ROLE_NM IS '역할명';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.ROLE_DESC IS '역할설명';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_M.DATA_UPD_DTM IS '데이터수정일시';

CREATE TABLE TB_RPJTE_ROLE_MENU_M (
ROLE_CD VARCHAR2(20) NOT NULL,
MNU_ID VARCHAR2(50) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011769 CHECK ("ROLE_CD" IS NOT NULL),
CONSTRAINT SYS_C0011770 CHECK ("MNU_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_ROLE_MENU_M_PK PRIMARY KEY (ROLE_CD,MNU_ID)
);


COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.MNU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_MENU_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_ROLE_EMP_M (
ROLE_CD VARCHAR2(20) NOT NULL,
USER_ID VARCHAR2(50) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011767 CHECK ("ROLE_CD" IS NOT NULL),
CONSTRAINT SYS_C0011768 CHECK ("USER_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_ROLE_EMP_M_PK PRIMARY KEY (ROLE_CD,USER_ID)
);


COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.USER_ID IS '사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_EMP_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_API_M (
API_ID VARCHAR2(50) NOT NULL,
API_NM VARCHAR2(100) NULL,
API_URL VARCHAR2(500) NULL,
USE_YN VARCHAR2(1) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
HTTP_MTHD_CD VARCHAR2(50) NULL,
CONSTRAINT SYS_C0011773 CHECK ("API_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_API_M_PK PRIMARY KEY (API_ID)
);

COMMENT ON COLUMN TB_RPJTE_API_M.API_ID IS 'API ID';
COMMENT ON COLUMN TB_RPJTE_API_M.API_NM IS 'API명';
COMMENT ON COLUMN TB_RPJTE_API_M.API_URL IS 'APIURL주소';
COMMENT ON COLUMN TB_RPJTE_API_M.HTTP_MTHD_CD IS 'HTTP방법코드';
COMMENT ON COLUMN TB_RPJTE_API_M.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_API_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_ROLE_API_M (
ROLE_CD VARCHAR2(20) NOT NULL,
API_ID VARCHAR2(50) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT SYS_C0011774 CHECK ("ROLE_CD" IS NOT NULL),
CONSTRAINT SYS_C0011775 CHECK ("API_ID" IS NOT NULL),
CONSTRAINT TB_RPJTE_ROLE_API_M_PK PRIMARY KEY (ROLE_CD,API_ID)

);

COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.ROLE_CD IS 'API ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.API_ID IS 'API ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_API_M.DATA_UPD_DTM IS '데이터수정일시';


CREATE TABLE TB_RPJTE_ROLE_DEPT_M (
ROLE_CD VARCHAR2(20) NOT NULL,
DEPT_CD VARCHAR2(20) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM DATE DEFAULT SYSDATE  NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM DATE DEFAULT SYSDATE  NULL,
CONSTRAINT TB_RPJTE_ROLE_DEPT_M_PK PRIMARY KEY (ROLE_CD,DEPT_CD)
);


COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.ROLE_CD IS '역할코드';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DEPT_CD IS '부서코드';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_INS_USER_ID IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_INS_USER_IP IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_INS_DTM IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_UPD_USER_ID IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_UPD_USER_IP IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_ROLE_DEPT_M.DATA_UPD_DTM IS '데이터수정일시';

create table TB_RPJTE_APR_DLGT_M
(
APR_DLGT_NO      NUMBER(20) NOT NULL,
APR_DLGT_USER_ID VARCHAR2(50) NOT NULL,
APR_DELE_USER_ID VARCHAR2(50) NOT NULL,
APR_DLGT_ST_DT   VARCHAR2(8) NOT NULL,
APR_DLGT_END_DT  VARCHAR2(8) NOT NULL,
USE_YN           VARCHAR2(1) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL,
CONSTRAINT TB_RPJTE_APR_DLGT_M_PK PRIMARY KEY (APR_DLGT_NO)
)
;
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.APR_DLGT_NO
IS '결재위임번호';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.APR_DLGT_USER_ID
IS '결재위임사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.APR_DELE_USER_ID
IS '결재수임사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.APR_DLGT_ST_DT
IS '결재위임시작일자';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.APR_DLGT_END_DT
IS '결재위임종료일자';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.USE_YN
IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_APR_DLGT_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE TABLE TB_RPJTE_BBS_M
(
BBM_NO            NUMBER(22,0) NOT NULL,
BBS_TP_CD         VARCHAR2(10) NULL,
BBM_SORT_ORD      NUMBER(22,0) NULL,
BBM_TIT_NM        VARCHAR2(300) NULL,
BBM_CTN           CLOB,
SMRY_CTN          VARCHAR2(4000) NULL,
ATCH_FILE_GR_ID   VARCHAR2(50) NULL,
HTAG_CTN          VARCHAR2(300) NULL,
IMPT_YN           VARCHAR2(1) NULL,
USE_YN            VARCHAR2(1) NULL,
BBM_VWCT          NUMBER(22,0) NULL,
PTUP_END_DT       VARCHAR2(8) NULL,
NOTI_USE_YN       VARCHAR2(1) NULL,
POUP_USE_YN       VARCHAR2(1) NULL,
POUP_ST_DTM       DATE NULL,
POUP_END_DTM      DATE NULL,
POUP_EPS_NUSE_DDN NUMBER(7,0) NULL,
BBM_CLSF_CD       VARCHAR2(50) NULL,
PTUP_TGT_COP_CD   VARCHAR2(10) NULL,
DATA_INS_USER_ID  VARCHAR2(50) NULL,
DATA_INS_USER_IP  VARCHAR2(40) NULL,
DATA_INS_DTM      DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID  VARCHAR2(50) NULL,
DATA_UPD_USER_IP  VARCHAR2(40) NULL,
DATA_UPD_DTM      DATE DEFAULT SYSDATE NULL
);

COMMENT ON TABLE TB_RPJTE_BBS_M
IS '게시판기본';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_NO
IS '게시글번호';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBS_TP_CD
IS '게시판유형코드';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_SORT_ORD
IS '게시글정렬순서';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_TIT_NM
IS '게시글제목명';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_CTN
IS '게시글내용';
COMMENT ON COLUMN TB_RPJTE_BBS_M.SMRY_CTN
IS '요약내용';
COMMENT ON COLUMN TB_RPJTE_BBS_M.ATCH_FILE_GR_ID
IS '첨부파일그룹ID';
COMMENT ON COLUMN TB_RPJTE_BBS_M.HTAG_CTN
IS '해시태그내용';
COMMENT ON COLUMN TB_RPJTE_BBS_M.IMPT_YN
IS '중요여부';
COMMENT ON COLUMN TB_RPJTE_BBS_M.USE_YN
IS '사용여부';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_VWCT
IS '게시글조회수';
COMMENT ON COLUMN TB_RPJTE_BBS_M.PTUP_END_DT
IS '게시종료일자';
COMMENT ON COLUMN TB_RPJTE_BBS_M.NOTI_USE_YN
IS '공지사용여부';
COMMENT ON COLUMN TB_RPJTE_BBS_M.POUP_USE_YN
IS '팝업사용여부';
COMMENT ON COLUMN TB_RPJTE_BBS_M.POUP_ST_DTM
IS '팝업시작일시';
COMMENT ON COLUMN TB_RPJTE_BBS_M.POUP_END_DTM
IS '팝업종료일시';
COMMENT ON COLUMN TB_RPJTE_BBS_M.POUP_EPS_NUSE_DDN
IS '팝업노출미사용일수';
COMMENT ON COLUMN TB_RPJTE_BBS_M.BBM_CLSF_CD
IS '게시글분류코드';
COMMENT ON COLUMN TB_RPJTE_BBS_M.PTUP_TGT_COP_CD
IS '게시대상법인코드';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_BBS_M.DATA_UPD_DTM
IS '데이터수정일시';
alter table TB_RPJTE_BBS_M
add constraint TB_RPJTE_BBS_M_PK primary key (BBM_NO);

CREATE TABLE TB_RPJTE_BBS_RE_D
(
BBM_NO           NUMBER NOT NULL,
BBM_RE_NO        NUMBER NOT NULL,
BBM_RE_CTN       VARCHAR2(1000) NOT NULL,
RE_DEL_YN        VARCHAR2(1) NOT NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL
)
;
COMMENT ON TABLE TB_RPJTE_BBS_RE_D
IS '게시판댓글상세';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.BBM_NO
IS '게시글번호';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.BBM_RE_NO
IS '게시글댓글번호';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.BBM_RE_CTN
IS '게시글댓글내용';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.RE_DEL_YN
IS '댓글삭제여부';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_BBS_RE_D.DATA_UPD_DTM
IS '데이터수정일시';
ALTER TABLE TB_RPJTE_BBS_RE_D
ADD CONSTRAINT TB_RPJTE_BBS_RE_D_PK PRIMARY KEY (BBM_NO, BBM_RE_NO);

CREATE TABLE TB_RPJTE_DT_M
(
COP_CD           VARCHAR2(10) NOT NULL,
SCAL_DT          VARCHAR2(8) NOT NULL,
SCAL_YY          VARCHAR2(4) NULL,
SCAL_MM          VARCHAR2(2) NULL,
SCAL_DD          VARCHAR2(2) NULL,
LCAL_DT          VARCHAR2(8) NULL,
DYWK_NO_CD       VARCHAR2(1) NULL,
YYWK             VARCHAR2(6) NULL,
MM_WCT           NUMBER(3) NULL,
HLDY_YN          VARCHAR2(1) NULL,
HLDY_NM          VARCHAR2(30) NULL,
OPT_VAL_NM1      VARCHAR2(100) NULL,
OPT_VAL_NM2      VARCHAR2(100) NULL,
OPT_VAL_NM3      VARCHAR2(100) NULL,
OPT_VAL_NM4      VARCHAR2(100) NULL,
OPT_VAL_NM5      VARCHAR2(100) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50),
DATA_UPD_USER_IP VARCHAR2(40),
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL
)
;
COMMENT ON TABLE TB_RPJTE_DT_M
IS '날짜기본';
COMMENT ON COLUMN TB_RPJTE_DT_M.COP_CD
IS '법인코드';
COMMENT ON COLUMN TB_RPJTE_DT_M.SCAL_DT
IS '양력일자';
COMMENT ON COLUMN TB_RPJTE_DT_M.SCAL_YY
IS '양력년도';
COMMENT ON COLUMN TB_RPJTE_DT_M.SCAL_MM
IS '양력월';
COMMENT ON COLUMN TB_RPJTE_DT_M.SCAL_DD
IS '양력일';
COMMENT ON COLUMN TB_RPJTE_DT_M.LCAL_DT
IS '음력일자';
COMMENT ON COLUMN TB_RPJTE_DT_M.DYWK_NO_CD
IS '요일번호코드';
COMMENT ON COLUMN TB_RPJTE_DT_M.YYWK
IS '년주차수';
COMMENT ON COLUMN TB_RPJTE_DT_M.MM_WCT
IS '월주차수';
COMMENT ON COLUMN TB_RPJTE_DT_M.HLDY_YN
IS '휴일여부';
COMMENT ON COLUMN TB_RPJTE_DT_M.HLDY_NM
IS '휴일명';
COMMENT ON COLUMN TB_RPJTE_DT_M.OPT_VAL_NM1
IS '옵션값명1';
COMMENT ON COLUMN TB_RPJTE_DT_M.OPT_VAL_NM2
IS '옵션값명2';
COMMENT ON COLUMN TB_RPJTE_DT_M.OPT_VAL_NM3
IS '옵션값명3';
COMMENT ON COLUMN TB_RPJTE_DT_M.OPT_VAL_NM4
IS '옵션값명4';
COMMENT ON COLUMN TB_RPJTE_DT_M.OPT_VAL_NM5
IS '옵션값명5';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_DT_M.DATA_UPD_DTM
IS '데이터수정일시';
ALTER TABLE TB_RPJTE_DT_M
ADD CONSTRAINT TB_RPJTE_DT_M_PK PRIMARY KEY (COP_CD, SCAL_DT);

CREATE TABLE TB_RPJTE_EML_SNDO_LOG_M
(
EML_SNDO_SEQ     NUMBER(18) NOT NULL,
EML_LOG_SEQ      NUMBER(18) NOT NULL,
EML_TP_CD        VARCHAR2(20) NULL,
EML_TIT_NM       VARCHAR2(100) NULL,
EML_RCVR_LST_CTN VARCHAR2(4000) NOT NULL,
SED_EMAL         VARCHAR2(100) NOT NULL,
SED_DTM          DATE NOT NULL,
EML_TRNM_STAT_CD VARCHAR2(20) NULL,
EML_TRNM_RLT_CTN VARCHAR2(200) NULL,
EML_BDY_CTN      VARCHAR2(4000) NULL,
APR_REQ_ID       VARCHAR2(50) NULL,
OPT_VAL_NM1      VARCHAR2(100) NULL,
OPT_VAL_NM2      VARCHAR2(100) NULL,
OPT_VAL_NM3      VARCHAR2(100) NULL,
OPT_VAL_NM4      VARCHAR2(100) NULL,
OPT_VAL_NM5      VARCHAR2(100) NULL,
DATA_INS_USER_ID VARCHAR2(50) NULL,
DATA_INS_USER_IP VARCHAR2(40) NULL,
DATA_INS_DTM     DATE DEFAULT SYSDATE NULL,
DATA_UPD_USER_ID VARCHAR2(50) NULL,
DATA_UPD_USER_IP VARCHAR2(40) NULL,
DATA_UPD_DTM     DATE DEFAULT SYSDATE NULL
);
COMMENT ON TABLE TB_RPJTE_EML_SNDO_LOG_M
IS '메일발송로그기본';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_SNDO_SEQ
IS '이메일발송순번';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_LOG_SEQ
IS '이메일로그순번';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_TP_CD
IS '이메일유형코드';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_RCVR_LST_CTN
IS '이메일수신자목록내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.SED_EMAL
IS '발신이메일주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.SED_DTM
IS '발신일시';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_TRNM_STAT_CD
IS '이메일전송상태코드';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_TRNM_RLT_CTN
IS '이메일전송결과내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.EML_BDY_CTN
IS '이메일본문내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.APR_REQ_ID
IS '결재요청ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.OPT_VAL_NM1
IS '옵션값명1';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.OPT_VAL_NM2
IS '옵션값명2';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.OPT_VAL_NM3
IS '옵션값명3';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.OPT_VAL_NM4
IS '옵션값명4';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.OPT_VAL_NM5
IS '옵션값명5';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_LOG_M.DATA_UPD_DTM
IS '데이터수정일시';
CREATE INDEX TB_RPJTE_EML_SNDO_LOG_M_IX01 ON TB_RPJTE_EML_SNDO_LOG_M (SED_DTM);
ALTER TABLE TB_RPJTE_EML_SNDO_LOG_M
ADD CONSTRAINT TB_RPJTE_EML_SNDO_LOG_M_PK PRIMARY KEY (EML_SNDO_SEQ, EML_LOG_SEQ);

CREATE TABLE TB_RPJTE_LOGN_LOG_M
(
CONT_LOG_ID      VARCHAR2(50) NOT NULL,
CONT_DTM         DATE DEFAULT SYSDATE NOT NULL,
CONT_USER_ID     VARCHAR2(50) NOT NULL,
CONT_IP          VARCHAR2(40),
DATA_INS_USER_ID VARCHAR2(50),
DATA_INS_USER_IP VARCHAR2(40),
DATA_INS_DTM     DATE DEFAULT SYSDATE,
DATA_UPD_USER_ID VARCHAR2(50),
DATA_UPD_USER_IP VARCHAR2(40),
DATA_UPD_DTM     DATE DEFAULT SYSDATE
);

COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.CONT_LOG_ID
IS '접속로그ID';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.CONT_DTM
IS '접속일시';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.CONT_USER_ID
IS '접속사용자ID';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.CONT_IP
IS '접속IP주소';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_LOGN_LOG_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE INDEX TB_RPJTE_LOGN_LOG_M_IX01 ON TB_RPJTE_LOGN_LOG_M (CONT_DTM);

ALTER TABLE TB_RPJTE_LOGN_LOG_M
ADD CONSTRAINT TB_RPJTE_LOGN_LOG_M_PK PRIMARY KEY (CONT_LOG_ID);

CREATE TABLE TB_RPJTE_MNU_ACES_LOG_M
(
ACES_LOG_ID      VARCHAR2(50) NOT NULL,
MNU_ID           VARCHAR2(50) NOT NULL,
CONT_DTM         DATE DEFAULT SYSDATE NOT NULL,
CONT_USER_ID     VARCHAR2(50),
CONT_IP          VARCHAR2(40),
DATA_INS_USER_ID VARCHAR2(50),
DATA_INS_USER_IP VARCHAR2(40),
DATA_INS_DTM     DATE DEFAULT SYSDATE,
DATA_UPD_USER_ID VARCHAR2(50),
DATA_UPD_USER_IP VARCHAR2(40),
DATA_UPD_DTM     DATE DEFAULT SYSDATE
);
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.ACES_LOG_ID
IS '접근로그ID';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.MNU_ID
IS '메뉴ID';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.CONT_DTM
IS '접속일시';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.CONT_USER_ID
IS '접속사용자ID';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.CONT_IP
IS '접속IP주소';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_MNU_ACES_LOG_M.DATA_UPD_DTM
IS '데이터수정일시';
CREATE INDEX TB_RPJTE_MNU_ACES_LOG_M_IX01 ON TB_RPJTE_MNU_ACES_LOG_M (CONT_DTM);
CREATE INDEX TB_RPJTE_MNU_ACES_LOG_M_IX02 ON TB_RPJTE_MNU_ACES_LOG_M (CONT_USER_ID);
CREATE INDEX TB_RPJTE_MNU_ACES_LOG_M_IX03 ON TB_RPJTE_MNU_ACES_LOG_M (CONT_IP);

ALTER TABLE TB_RPJTE_MNU_ACES_LOG_M
ADD CONSTRAINT TB_RPJTE_MNU_ACES_LOG_M_PK PRIMARY KEY (ACES_LOG_ID);

CREATE TABLE TB_RPJTE_IF_LOG_M
(
IF_LOG_SEQ       NUMBER(22) NOT NULL,
IF_LOG_DTM       DATE NOT NULL,
IF_NM            VARCHAR2(300),
IF_DIVS_CD       VARCHAR2(20),
IF_TRMT_VAL_CTN  VARCHAR2(4000),
IF_REST_VAL_CTN  VARCHAR2(4000),
OPT_VAL_NM1      VARCHAR2(100),
OPT_VAL_NM2      VARCHAR2(100),
OPT_VAL_NM3      VARCHAR2(100),
OPT_VAL_NM4      VARCHAR2(100),
OPT_VAL_NM5      VARCHAR2(100),
DATA_INS_USER_ID VARCHAR2(50),
DATA_INS_USER_IP VARCHAR2(40),
DATA_INS_DTM     DATE DEFAULT SYSDATE,
DATA_UPD_USER_ID VARCHAR2(50),
DATA_UPD_USER_IP VARCHAR2(40),
DATA_UPD_DTM     DATE DEFAULT SYSDATE
);
COMMENT ON TABLE TB_RPJTE_IF_LOG_M
IS '인터페이스로그기본';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_LOG_SEQ
IS '인터페이스로그순번';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_LOG_DTM
IS '인터페이스로그일시';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_NM
IS '인터페이스명';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_DIVS_CD
IS '인터페이스구분코드';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_TRMT_VAL_CTN
IS '인터페이스송신값내용';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.IF_REST_VAL_CTN
IS '인터페이스수신값내용';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.OPT_VAL_NM1
IS '옵션값명1';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.OPT_VAL_NM2
IS '옵션값명2';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.OPT_VAL_NM3
IS '옵션값명3';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.OPT_VAL_NM4
IS '옵션값명4';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.OPT_VAL_NM5
IS '옵션값명5';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_IF_LOG_M.DATA_UPD_DTM
IS '데이터수정일시';
CREATE INDEX TB_RPJTE_IF_LOG_M_IX01 ON TB_RPJTE_IF_LOG_M (IF_LOG_DTM);
ALTER TABLE TB_RPJTE_IF_LOG_M
ADD CONSTRAINT TB_RPJTE_IF_LOG_M_PK PRIMARY KEY (IF_LOG_SEQ);


CREATE TABLE TB_RPJTE_EML_SNDO_QUE_M
(
EML_SNDO_SEQ     NUMBER(18) NOT NULL,
EML_TP_CD        VARCHAR2(20),
EML_TIT_NM       VARCHAR2(1000) NOT NULL,
EML_RCVR_LST_CTN VARCHAR2(4000) NOT NULL,
SED_EMAL         VARCHAR2(100) NOT NULL,
EML_SED_USER_NM  VARCHAR2(100),
SED_DTM          DATE,
EML_TRNM_STAT_CD VARCHAR2(20),
EML_TRNM_RLT_CTN VARCHAR2(200),
EML_DTL_CTN      CLOB,
APR_REQ_ID       VARCHAR2(50),
OPT_VAL_NM1      VARCHAR2(100),
OPT_VAL_NM2      VARCHAR2(100),
OPT_VAL_NM3      VARCHAR2(100),
OPT_VAL_NM4      VARCHAR2(100),
OPT_VAL_NM5      VARCHAR2(100),
DATA_INS_USER_ID VARCHAR2(50),
DATA_INS_USER_IP VARCHAR2(40),
DATA_INS_DTM     DATE DEFAULT SYSDATE,
DATA_UPD_USER_ID VARCHAR2(50),
DATA_UPD_USER_IP VARCHAR2(40),
DATA_UPD_DTM     DATE DEFAULT SYSDATE
);
COMMENT ON TABLE TB_RPJTE_EML_SNDO_QUE_M
IS '메일발송큐기본';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_SNDO_SEQ
IS '이메일발송순번';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_TP_CD
IS '이메일유형코드';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_TIT_NM
IS '이메일제목명';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_RCVR_LST_CTN
IS '이메일수신자목록내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.SED_EMAL
IS '발신이메일주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_SED_USER_NM
IS '이메일발신사용자명';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.SED_DTM
IS '발신일시';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_TRNM_STAT_CD
IS '이메일전송상태코드';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_TRNM_RLT_CTN
IS '이메일전송결과내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.EML_DTL_CTN
IS '이메일상세내용';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.APR_REQ_ID
IS '결재요청ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.OPT_VAL_NM1
IS '옵션값명1';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.OPT_VAL_NM2
IS '옵션값명2';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.OPT_VAL_NM3
IS '옵션값명3';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.OPT_VAL_NM4
IS '옵션값명4';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.OPT_VAL_NM5
IS '옵션값명5';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_INS_USER_ID
IS '데이터입력사용자ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_INS_USER_IP
IS '데이터입력사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_INS_DTM
IS '데이터입력일시';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_UPD_USER_ID
IS '데이터수정사용자ID';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_UPD_USER_IP
IS '데이터수정사용자IP주소';
COMMENT ON COLUMN TB_RPJTE_EML_SNDO_QUE_M.DATA_UPD_DTM
IS '데이터수정일시';

CREATE INDEX TB_RPJTE_EML_SNDO_QUE_M_IX01 ON TB_RPJTE_EML_SNDO_QUE_M (EML_TRNM_RLT_CTN);
ALTER TABLE TB_RPJTE_EML_SNDO_QUE_M
ADD CONSTRAINT TB_RPJTE_EML_SNDO_QUE_M_PK PRIMARY KEY (EML_SNDO_SEQ);